lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.key'
    public_key: '%kernel.project_dir%/config/jwt/public.key'
    pass_phrase: 'your_passphrase_here'
    token_ttl: 3600 # 1 hour 